### ISSUE TITLE
mvn exec:java -Dexec.mainClass="io.github.xdiamond.example.ClientExampleMain"运行报错

### ISSUE THREAD

**Issue by helloworldtang** [hengyunabc/xdiamond#20]
[WARNING]
java.lang.ClassNotFoundException: io.github.xdiamond.example.ClientExampleMain
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:281)
        at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:36 min

**Comment by hengyunabc** [comment]
先 mvn clean package -DskipTests 编绎生成target目录。
