### ISSUE TITLE
xdiamond 连接server报错

### ISSUE THREAD

**Issue by yyyl** [hengyunabc/xdiamond#32]
[ERROR] io.github.xdiamond.client.XDiamondConfig - load xdiamond config from server error! test|captcha|1.0|product
java.util.concurrent.TimeoutException: null
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:49)
	at io.github.xdiamond.client.XDiamondConfig.init(XDiamondConfig.java:127)

[INFO] io.github.xdiamond.client.net.XDiamondClient - Reconnecting to 10.0.0.97:8804
[INFO] io.github.xdiamond.client.net.XDiamondClient - connection to 10.0.0.97:8804 success.

[WARN] org.springframework.context.annotation.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xDiamondConfig' defined in class path resource [spring-context-springboot-example.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException

**Comment by hengyunabc** [comment]
用nc或者其它的网络工具，检查下server是否启动成功了

**Comment by yyyl** [comment]
上面的问题解决了，端口号没有暴露出来。
还有个问题想请教一下，一个项目里面监听多个project的配置项（例如A个B两个项目），那么每个xDiamondConfig  可以指定listener吗？就是一个listener A监听项目A中的配置项，listener B监听项目B中的配置，因为A和B中有可能存在配置名（key）相同的情况。

**Comment by hengyunabc** [comment]
对于一个项目来说，它的配置就是只有一份，参考wiki里的设计说明
