### ISSUE TITLE
安装部署启动tomcat报错Error while adding the mapper 'interface io.github.xdiamond.persistence.ProjectMapper' to configuration.

### ISSUE THREAD

**Issue by Anonymity124** [hengyunabc/xdiamond#36]
org.mybatis.spring.mapper.MapperFactoryBean - Error while adding the mapper 'interface io.github.xdiamond.persistence.ProjectMapper' to configuration.
org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: org.apache.ibatis.cache.CacheException: Could not instantiate cache implementation (class io.github.hengyunabc.mybatis.FacadeCache). Cause: java.lang.reflect.InvocationTargetException
        at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:120) ~[mybatis-3.2.7.jar:3.2.7]
        at org.apache.ibatis.builder.xml.XMLMapperBuilder.parse(XMLMapperBuilder.java:92) ~[mybatis-3.2.7.jar:3.2.7]
        at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.loadXmlResource(MapperAnnotationBuilder.java:164) ~[mybatis-3.2.7.jar:3.2.7]
        at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parse(MapperAnnotationBuilder.java:118) ~[mybatis-3.2.7.jar:3.2.7]
        at org.apache.ibatis.binding.MapperRegistry.addMapper(MapperRegistry.java:71) ~[mybatis-3.2.7.jar:3.2.7]
        at org.apache.ibatis.session.Configuration.addMapper(Configuration.java:651) ~[mybatis-3.2.7.jar:3.2.7]

**Comment by Anonymity124** [comment]
This issue has been fixed。。^_^
