### ISSUE TITLE
Fastjson在序列化时要关闭引用功能

### ISSUE THREAD

**Issue by hengyunabc** [hengyunabc/xdiamond#6]
https://github.com/alibaba/fastjson/wiki/%E5%BE%AA%E7%8E%AF%E5%BC%95%E7%94%A8

否则有可能，xdiamond client不支持`$ref`这样子的语法，就会报错。fastjson的坑。。

**Comment by hengyunabc** [comment]
``` java
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 30 30 30 22 2c 22 76 65 72 73 69 6f 6e 22 3a 30 |000","version":0|
|00000010| 7d 2c 22 66 72 6f 6d 50 72 6f 66 69 6c 65 22 3a |},"fromProfile":|
|00000020| 22 64 65 76 22 2c 22 66 72 6f 6d 50 72 6f 6a 65 |"dev","fromProje|
|00000030| 63 74 22 3a 7b 22 24 72 65 66 22 3a 22 24 2e 72 |ct":{"$ref":"$.r|
|00000040| 65 73 75 6c 74 2e 63 6f 6e 66 69 67 73 5b 33 31 |esult.configs[31|
|00000050| 5d 2e 66 72 6f 6d 50 72 6f 6a 65 63 74 22 7d 7d |].fromProject"}}|
|00000060| 5d 7d 2c 22 73 75 63 63 65 73 73 22 3a 74 72 75 |]},"success":tru|
|00000070| 65 2c 22 74 79 70 65 22 3a 32 7d                |e,"type":2}     |
+--------+-------------------------------------------------+----------------+
13:54:45.596 [nioEventLoopGroup-2-1] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException
    at com.alibaba.fastjson.JSON.handleResovleTask(JSON.java:237) ~[fastjson-1.1.15.jar:?]
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:277) ~[fastjson-1.1.15.jar:?]
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:260) ~[fastjson-1.1.15.jar:?]
    at com.alibaba.fastjson.JSON.parseObject(JSON.java:243) ~[fastjson-1.1.15.jar:?]
    at io.xdiamond.common.net.Message.dataToResponse(Message.java:86) ~[classes/:?]
    at io.github.xdiamond.client.net.ClientHandler.channelRead0(ClientHandler.java:81) ~[classes/:?]
    at io.github.xdiamond.client.net.ClientHandler.channelRead0(ClientHandler.java:1) ~[classes/:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161) [netty-codec-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254) [netty-handler-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:283) [netty-handler-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-common-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.24.Final.jar:4.0.24.Final]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_67]
```
